//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelProduct:IProduct
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public double Rating { get; set; }
        public double Price { get; set; }
        public System.DateTime Date { get; set; }
        public bool Booked { get; set; }
        public bool Saved { get; set; }

        public bool Book()
        {
            if (Booked == true)
            {
                Booked = false;
                return false;
            }
            else
                Booked = true;
            return true;
        }

        public bool Save()
        {
            if (Saved == true)
            {
                Saved = false;
                return false;
            }
            else
                Saved = true;
            return true;
        }
    }
}
