//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InventoryDatabaseEntities : DbContext
    {
        public InventoryDatabaseEntities()
            : base("name=InventoryDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActivityProduct> ActivityProducts { get; set; }
        public virtual DbSet<AirProduct> AirProducts { get; set; }
        public virtual DbSet<CarProduct> CarProducts { get; set; }
        public virtual DbSet<HotelProduct> HotelProducts { get; set; }
        public virtual DbSet<Booked> Bookeds { get; set; }
        public virtual DbSet<Saved> Saveds { get; set; }
    }
}
