//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesignPatterns
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarProduct:IProduct
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<double> Price { get; set; }
        public bool Booked { get; set; }

        public void Book()
        {
            throw new NotImplementedException();
        }

        public void Save()
        {
            throw new NotImplementedException();
        }

        public string TypeOfProduct()
        {
            throw new NotImplementedException();
        }
    }
}
